# Camunda Platform 7
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
  autoDeploy:
    enabled: true
  disable-backoff-strategy: true
  basic-auth:
    username: ${CAMUNDA_USERNAME:demo}
    password: ${CAMUNDA_PASSWORD:demo}

server:
  port: 8081
